version: '3.4'

services:
  openSleigh.samples.infrastructure.mongodb:
    image: mongo:latest
    container_name: openSleigh.samples.infrastructure.mongodb    
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017    
  
  openSleigh.samples.infrastructure.rabbitmq:        
    image: rabbitmq:3-management-alpine
    container_name: openSleigh.samples.infrastructure.rabbitmq    
    restart: always
    environment:
     RABBITMQ_DEFAULT_VHOST: "/"
    ports:     
      - "15671:15671"
      - "15672:15672"   
      - "5672:5672"